# Cross-validate Dewdrop's Stats.jl against the reference stats.py outputs (reference
# generated by stats_reference.py in the brainpy env). jax computes in float32, so jax-backed
# observables (susceptibility / spike_spectrum / temporal_average / radial_autocorrelation) are
# compared at float32 tolerance; integer/numpy ones are exact-ish. Run:
#   julia +1.12 --project=test test/simulator_comparisons/stats_validation/compare_stats.jl
using Dewdrop
using Test

include(joinpath(@__DIR__, "stats_reference_data.jl"))   # defines `const REF`

S = permutedims(REF.S)                                    # (T,N) → Dewdrop (N,T)
V = permutedims(REF.V)
dt = REF.dt
cg4 = coarsegrain(S, 4; dims = 2)                         # reused (bin = 0.4 ms / 0.1 = 4 steps)

report(name, err) = println(rpad(name, 26), "max|Δ| = ", err)

@testset "Dewdrop Stats.jl ≡ reference stats.py" begin
    # integer / exact
    @test coarsegrain(S, 4; dims = 2) == permutedims(REF.coarsegrain)
    @test mua(S) == REF.mua
    @test mua(cg4) == REF.mua_binned

    # numpy float64
    eh = maximum(abs.(susceptibility(S) - REF.susceptibility)); report("susceptibility", eh)
    @test susceptibility(S) ≈ REF.susceptibility rtol = 1.0e-4
    @test susceptibility(cg4) ≈ REF.susceptibility_binned rtol = 1.0e-4

    tav = temporal_average(V)
    report("temporal_average", maximum(abs.(tav - REF.temporal_average)))
    @test tav ≈ REF.temporal_average rtol = 1.0e-4

    gh, gc = grand_distribution(vec(REF.V), 10)
    report("grand_distribution counts", maximum(abs.(gh - REF.grand_hist)))
    @test sum(gh) == sum(REF.grand_hist)
    @test maximum(abs.(gh - REF.grand_hist)) ≤ 3        # float32 bin-edge quirk in stats.py
    @test gc ≈ REF.grand_centers rtol = 1.0e-4

    # jax float32 spectral / spatial
    psd, _ = power_spectrum(S; n_segments = 2, dt = dt)
    report("power_spectrum (PSD)", maximum(abs.(psd - REF.psd)))
    @test psd ≈ REF.psd rtol = 1.0e-3

    gr, rb = radial_autocorrelation(S, REF.positions; dr = 1.0)
    report("radial_autocorrelation", maximum(abs.(gr - REF.radial_gr)))
    @test rb ≈ REF.radial_rbins
    @test gr ≈ REF.radial_gr atol = 2.0e-3

    # efficiency (2×2 spatial bins, matching the python neuron grouping exactly)
    GX = REF.GX
    bin_indices = Matrix{Vector{Int}}(undef, 2, 2)
    for bi in 0:1, bj in 0:1
        bin_indices[bi + 1, bj + 1] = [i * GX + j + 1 for i in (bi * 4):(bi * 4 + 3) for j in (bj * 4):(bj * 4 + 3)]
    end
    eta = efficiency(S, bin_indices, 0.4; dt = dt)
    report("efficiency", maximum(abs.(eta - REF.efficiency)))
    @test eta ≈ REF.efficiency rtol = 1.0e-3
end
