using Dewdrop
using Documenter
using Documenter: Documenter
using Documenter.Remotes: GitHub
using DocumenterVitepress
using Downloads
using YAML

# --- Fathom auto-generated colours ---------------------------------------------------------------
# Fetch the Fathom palette (colors.yaml) at build time and regenerate the CSS custom-property palette
# the docs theme reads. The semantic light/dark mapping lives in `style.css`, which `@import`s this
# file --- so the docs theme tracks the Fathom palette automatically (mirrors TimeseriesDocs.jl).
function generate_palette_css(;
        url = "https://raw.githubusercontent.com/brendanjohnharris/Fathom.jl/main/test/colors.yaml",
        out = joinpath(@__DIR__, "src", ".vitepress", "theme", "palette.css"),
    )
    mkpath(dirname(out))
    palette = try
        YAML.load(sprint(io -> Downloads.download(url, io)))
    catch err
        @warn "Could not fetch the Fathom palette; keeping any existing palette.css" err
        return out
    end
    io = IOBuffer()
    println(io, "/* Generated by docs/make.jl from $url. Do not edit by hand. */")
    println(io, ":root {")
    for (name, shades) in palette
        shades isa AbstractDict || continue
        for shade in ("base", "darker", "light", "lighter", "dark")
            haskey(shades, shade) && println(io, "    --c-$name-$shade: $(shades[shade]);")
        end
        println(io)
    end
    println(io, "}")
    write(out, take!(io))
    @info "Wrote Fathom palette CSS" out colours = length(palette)
    return out
end

generate_palette_css()

format = DocumenterVitepress.MarkdownVitepress(;
    repo = "github.com/brendanjohnharris/Dewdrop.jl",
    devbranch = "main",
    devurl = "dev",
)

# the LoopVectorization extension (Turbo kernels) is documented too, when it is loaded.
const TURBO_EXT = Base.get_extension(Dewdrop, :DewdropLoopVectorizationExt)
modules = TURBO_EXT === nothing ? [Dewdrop] : [Dewdrop, TURBO_EXT]

pages = [
    "Home" => "index.md",
    "Guide" => [
        "Choosing a backend" => "guide/backends.md",
        "Turbo & model specialization" => "guide/turbo.md",
    ],
    "Reference" => "reference.md",
]

makedocs(;
    authors = "brendanjohnharris <bhar9988@uni.sydney.edu.au> and contributors",
    sitename = "Dewdrop",
    format,
    remotes = Dict(pkgdir(Dewdrop) => (GitHub("brendanjohnharris", "Dewdrop.jl"), "main")),
    doctest = false,
    warnonly = [:cross_references, :missing_docs, :docs_block, :example_block],
    modules,
    pages,
)

DocumenterVitepress.deploydocs(;
    repo = "github.com/brendanjohnharris/Dewdrop.jl",
    target = "build",
    branch = "gh-pages",
    devbranch = "main",
    push_preview = true,
)
